default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'halal_rails' }%>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'password' }%>
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' }%>

development:
  <<: *default
  database: development

production:
  <<: *default
  database: production
