# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Word.create(name: "豚", english: "pork")
Word.create(name: "イノシシ", english: "boar")
Word.create(name: "ポークエキス", english: "Animal extract")
Word.create(name: "ライオン", english: "Lion")
Word.create(name: "犬", english: "dog")
Word.create(name: "オオカミ", english: "wolf")
Word.create(name: "虎", english: "tiger")
Word.create(name: "鷲", english: "eagle")
Word.create(name: "梟", english: "owl")
Word.create(name: "鷹", english: "hawk")
Word.create(name: "猛禽類", english: "Bird of prey")
Word.create(name: "蛙", english: "frog")
Word.create(name: "蛇", english: "snake")
Word.create(name: "イカ", english: "squid")
Word.create(name: "タコ", english: "octopus")
Word.create(name: "エビ", english: "shrimp")
Word.create(name: "カニ", english: "crab")
Word.create(name: "ロブスター", english: "lobster")
Word.create(name: "グリセリン", english: "Glycerin")
Word.create(name: "乳化剤", english: "emulsifier")
Word.create(name: "酒", english: "Alcohol(sake)")
Word.create(name: "みりん", english: "sweet sake")
Word.create(name: "添加物", english: "Additive")
Word.create(name: "醸造酢", english: "Brewed vinegar")
Word.create(name: "ラード", english: "lard")
Word.create(name: "ショートニング", english: "shortening")
Word.create(name: "ビーフエキス", english: "beef")
Word.create(name: "鳥エキス", english: "chicken")
Word.create(name: "チキンエキス", english: "chicken")
Word.create(name: "とんこつ", english: "pork bone")
Word.create(name: "豚骨", english: "prok bone")
Word.create(name: "肉エキス", english: "daging")
Word.create(name: "ビーフコンソメ", english: "beef consome")
Word.create(name: "コンソメ", english: "concome")
Word.create(name: "洋酒", english: "wine")
Word.create(name: "", english: "")
Word.create(name: "アルコール", english: "alcohol")
Word.create(name: "ブランデー", english: "brandy")
Word.create(name: "ラム", english: "western wine")
Word.create(name: "", english: "")
Word.create(name: "醸造", english: "brewed")
Word.create(name: "酸化防止剤", english: "Antioxidant")
Word.create(name: "マーガリン", english: "margarin")
Word.create(name: "ワイン", english: "wine")
Word.create(name: "ゼラチン", english: "gelatin")
Word.create(name: "膨張剤", english: "baking powder")
Word.create(name: "リキュール", english: "liqueur")